### ISSUE TITLE
Width warping

### ISSUE THREAD

**Issue by goldfndr** [twpol/osm-tiles#7]
There is a strange width warping at https://osm-tiles.james-ross.co.uk/?map=20/47.617282/-122.189869 -- the southern west/east road is a single way (layer 0) from on-ramp (intersection) to off-ramp (just prior to bridge) so it shouldn't be a layer side-effect.

**Comment by twpol** [comment]
I'm going to guess that the tile on the left doesn't have a road segment from the right in its data. Looking at https://www.openstreetmap.org/query?lat=47.61729&lon=-122.18962 we have these ways forming a merge junction on the right-hand tile:

1. Secondary Road Northeast 8th Street
2. Motorway Road #161930315
3. Secondary Road Northeast 8th Street

If the left tile only has ways 1 and 2 (the two ways into the merge junction), and not way 3 (the merged way onwards), then it'll currently think that ways 1 and 2 are one road making a rather sharp corner, and attempt to draw them as such. However, [the code puts a limit on the sharpness of corners](https://github.com/twpol/osm-tiles/commit/e479257d160e03a22aad9e54f4673854d22540eb#diff-ddcd9a7cff6676044b86ffc843380e92R58) of about 120° (`cos(60) = 0.5`, and the angle there is between way and node), so you'll get some distorted roads.

I can probably fix this by changing the Overpass query, as I now need to have all ways that are in view, all of their points (including not in view), and **any other ways connected to any of those points**. I can also make the junction calculations smarter (they were going to get more sophisticated anyway) and make it discard this as a road continuation due to the sharp angle.
